### ISSUE TITLE
编译时pdnsd-alt报错

### ISSUE THREAD

**Issue by RayKr** [coolsnowwolf/lede#11447]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：挂全局，使用命令`make download -j1 V=s`，发现download时，pdnsd-alt包出错，最开始从各个源下载均404，copy链接出来在浏览器里尝试打开，也都是404（挂梯子的情况下）。最后从这个`https://github.com/shadowsocks/pdnsd.git/`库中下载`pdnsd-1.2.9b-par`包，但是发现这个库中latest版本是`pdnsd-1.2.9a-par`。

### (2) 路由器型号和固件版本

A：按教程步骤编译x86包

### (3) 详细日志

A：
```
make[2]: Entering directory '/home/raykr/lede/feeds/packages/net/pdnsd-alt'
mkdir -p /home/raykr/lede/dl
SHELL= flock /home/raykr/lede/tmp/.pdnsd-1.2.9b-par.tar.xz.flock -c '  	/home/raykr/lede/scripts/download.pl "/home/raykr/lede/dl" "pdnsd-1.2.9b-par.tar.xz" "e3e9c56cf91b12d8db73def2c247be2f726a052bed012f7a1e48946375f8e478" "" || (  /home/raykr/lede/scripts/dl_github_archive.py --dl-dir="/home/raykr/lede/dl" --url="https://github.com/shadowsocks/pdnsd.git" --version="a8e46ccba7b0fa2230d6c42ab6dcd92926f6c21d" --subdir="pdnsd-1.2.9b-par" --source="pdnsd-1.2.9b-par.tar.xz" --hash="e3e9c56cf91b12d8db73def2c247be2f726a052bed012f7a1e48946375f8e478" || ( 	echo "Checking out files from the git repository..."; mkdir -p /home/raykr/lede/tmp/dl && cd /home/raykr/lede/tmp/dl && rm -rf pdnsd-1.2.9b-par && [ \! -d pdnsd-1.2.9b-par ] && git clone  https://github.com/shadowsocks/pdnsd.git pdnsd-1.2.9b-par && (cd pdnsd-1.2.9b-par && git checkout a8e46ccba7b0fa2230d6c42ab6dcd92926f6c21d && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd pdnsd-1.2.9b-par && git log -1 --format='\''@%ct'\''` && rm -rf pdnsd-1.2.9b-par/.git && 	ar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c pdnsd-1.2.9b-par | 	xz -zc -7e > /home/raykr/lede/tmp/dl/pdnsd-1.2.9b-par.tar.xz && mv /home/raykr/lede/tmp/dl/pdnsd-1.2.9b-par.tar.xz /home/raykr/lede/dl/ && rm -rf pdnsd-1.2.9b-par; );  )    '
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/pdnsd-1.2.9b-par.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--       0   169    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/pdnsd-1.2.9b-par.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--       0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--       0   169    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/pdnsd-1.2.9b-par.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--       0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
Traceback (most recent call last):
  File "/home/raykr/lede/scripts/dl_github_archive.py", line 19, in <module>
    import ssl
  File "/usr/local/lib/python3.11/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named '_ssl'
Checking out files from the git repository...
Cloning into 'pdnsd-1.2.9b-par'...
fatal: unable to access 'https://github.com/shadowsocks/pdnsd.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
make[2]: *** [Makefile:58: /home/raykr/lede/dl/pdnsd-1.2.9b-par.tar.xz] Error 128
make[2]: Leaving directory '/home/raykr/lede/feeds/packages/net/pdnsd-alt'
time: package/feeds/packages/pdnsd-alt/download#0.37#0.25#123.08
    ERROR: package/feeds/packages/pdnsd-alt failed to build.
make[1]: *** [package/Makefile:116: package/feeds/packages/pdnsd-alt/download] Error 1
make[1]: Leaving directory '/home/raykr/lede'
make[1]: Entering directory '/home/raykr/lede'
make[2]: Entering directory '/home/raykr/lede/target/linux'
make[3]: Entering directory '/home/raykr/lede/target/linux/x86'
make[3]: Nothing to be done for 'download'.
make[3]: Leaving directory '/home/raykr/lede/target/linux/x86'
make[2]: Leaving directory '/home/raykr/lede/target/linux'
time: target/linux/download#0.06#0.10#0.12
make[1]: Leaving directory '/home/raykr/lede'
```

**Comment by bi4tms** [comment]
没看到下载没速度吗，优化你的网络环境
