### ISSUE TITLE
8月20日源码 glib-2.74.0 编译报错

### ISSUE THREAD

**Issue by DeemoTlz** [coolsnowwolf/lede#11463]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：glib-2.74.0 编译报错

### (2) 路由器型号和固件版本

A：Ubuntu 22.04.2 X86

### (3) 详细日志

A：../../../../build_dir/hostpkg/glib-2.74.0/meson.build:1925: WARNING: DEPRECATION: Option 'force_posix_threads' is deprecated and will be removed after GLib 2.72; please file an issue with your use case if you still require it
Run-time dependency threads found: YES
Header <pthread.h> has symbol "pthread_attr_setstacksize" : YES 
Header <pthread.h> has symbol "pthread_attr_setinheritsched" : YES 
Header <pthread.h> has symbol "pthread_condattr_setclock" : YES 
Header <pthread.h> has symbol "pthread_cond_timedwait_relative_np" : NO 
Header <pthread.h> has symbol "pthread_getname_np" : YES 
Header <sys/syscall.h> has symbol "SYS_sched_getattr" : YES 
Checking if "pthread_setname_np(const char*)" with dependency threads: links: NO 
Checking if "pthread_setname_np(pthread_t, const char*)" with dependency threads: links: YES 
Checking if "stack grows check" runs: NO (1)
Run-time dependency iconv found: YES
Looking for a fallback subproject for the dependency libpcre2-8 because:
Use of fallback dependencies is forced.
Downloading pcre2 source from https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.40/pcre2-10.40.tar.bz2
Traceback (most recent call last):
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/mesonmain.py", line 148, in run
    return options.run_func(options)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/msetup.py", line 294, in run
    app.generate()
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/interpreter.py", line 2554, in run
    super().run()
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 181, in evaluate_statement
    self.assignment(cur)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 566, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 179, in evaluate_statement
    return self.function_call(cur)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 454, in function_call
    res = func(node, func_args, kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 5 more times]
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 96, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 276, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/interpreter.py", line 1577, in func_dependency
    d = df.lookup(kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/dependencyfallbacks.py", line 347, in lookup
    dep = func(kwargs, func_args, func_kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/dependencyfallbacks.py", line 131, in _do_subproject
    self.interpreter.do_subproject(subp_name, 'meson', func_kwargs)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/interpreter.py", line 841, in do_subproject
    subdir = r.resolve(subp_name, method)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/wrap/wrap.py", line 334, in resolve
    self.get_file()
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/wrap/wrap.py", line 398, in get_file
    path = self.get_file_internal('source')
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/wrap/wrap.py", line 560, in get_file_internal
    self.download(what, cache_path)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/wrap/wrap.py", line 535, in download
    dhash, tmpfile = self.get_data(srcurl)
  File "/home/albrus/lede/staging_dir/host/bin/meson.py/mesonbuild/wrap/wrap.py", line 486, in get_data
    resp = urllib.request.urlopen(req, timeout=REQ_TIMEOUT)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

../../../../build_dir/hostpkg/glib-2.74.0/meson.build:2046:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
make[3]: *** [Makefile:120: /home/albrus/lede/build_dir/hostpkg/glib-2.74.0/.configured] Error 2
make[3]: Leaving directory '/home/albrus/lede/feeds/packages/libs/glib2'
time: package/feeds/packages/glib2/host-compile#7.09#6.97#16.69
    ERROR: package/feeds/packages/glib2 [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/glib2/host/compile] Error 1
make[2]: Leaving directory '/home/albrus/lede'
make[1]: *** [package/Makefile:110: /home/albrus/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/albrus/lede'
make: *** [/home/albrus/lede/include/toplevel.mk:231: world] Error 2

**Comment by DeemoTlz** [comment]
添加了两个 feed 源：
src-git kenzo https://github.com/kenzok8/openwrt-packages
src-git small https://github.com/kenzok8/small

**Comment by DeemoTlz** [comment]
测试编译选择了 open-vm-tools、open-vm-tools-fuse
`make package/feeds/packages/glib2/host/{clean,compile} V=s`
就会报错

**Comment by smallprogram** [comment]
+1 x86平台

**Comment by ywt114** [comment]
需要l大更新一下https://github.com/coolsnowwolf/packages项目下的/libs/glib2和/libs/pcre2两个文件，也可以\rm -rf feeds/packages/libs/glib2和svn co https://github.com/openwrt/packages/trunk/libs/glib2 feeds/packages/libs/glib2用官方最新源替换，然后glib2下的Makefile里把依赖项pcre2/host删除，因为单独替换glib2没有替换pcre2的话，会出现WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'pcre2/host', which does not exist，编译也正常但是强迫症影响观感。

**Comment by ywt114** [comment]
最好有大佬提交以下glib2和pcrec2的commit

**Comment by DeemoTlz** [comment]
> 需要l大更新一下[https://github.com/coolsnowwolf/packages项目下的/libs/glib2和/libs/pcre2两个文件，也可以\rm](https://github.com/coolsnowwolf/packages%E9%A1%B9%E7%9B%AE%E4%B8%8B%E7%9A%84/libs/glib2%E5%92%8C/libs/pcre2%E4%B8%A4%E4%B8%AA%E6%96%87%E4%BB%B6%EF%BC%8C%E4%B9%9F%E5%8F%AF%E4%BB%A5%5Crm) -rf feeds/packages/libs/glib2和svn co https://github.com/openwrt/packages/trunk/libs/glib2 feeds/packages/libs/glib2用官方最新源替换，然后glib2下的Makefile里把依赖项pcre2/host删除，因为单独替换glib2没有替换pcre2的话，会出现WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'pcre2/host', which does not exist，编译也正常但是强迫症影响观感。

谢谢哥哥指点，我试一下看看

**Comment by DeemoTlz** [comment]
按照 @ywt114 哥哥的指点，成功编译，感谢！整理下，有需要的可以试试：
`rm -rf feeds/packages/libs/glib2`
`svn co https://github.com/openwrt/packages/trunk/libs/glib2 feeds/packages/libs/glib2`
`vi feeds/packages/libs/glib2/Makefile` 第 29 行 -> `# HOST_BUILD_DEPENDS:=pcre2/host libffi/host`
