### ISSUE TITLE
编译时勾选python，导致失败

### ISSUE THREAD

**Issue by QYKing233** [coolsnowwolf/lede#12311]
### 详细叙述

setuptools可能版本冲突或者别的什么原因。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Orangepi R1 Plus LTS-RK3328

### 详细日志

Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      <string>:22: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      /home/king/openwrt/lede/tmp/pip-install-tt8lqps6/setuptools-scm_b7e62d5fd58443b6ad90dad118a9e3bc/src
      <pkg_resources.WorkingSet object at 0x58ef2e8bab10>
      Traceback (most recent call last):
        File "/home/king/openwrt/lede/tmp/pip-install-tt8lqps6/setuptools-scm_b7e62d5fd58443b6ad90dad118a9e3bc/src/setuptools_scm/version.py", line 11, in <module>
          from packaging.version import Version
      ModuleNotFoundError: No module named 'packaging'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/king/openwrt/lede/staging_dir/hostpkg/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/king/openwrt/lede/staging_dir/hostpkg/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/king/openwrt/lede/staging_dir/hostpkg/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/home/king/openwrt/lede/tmp/pip-build-env-vezp92h4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/home/king/openwrt/lede/tmp/pip-build-env-vezp92h4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/home/king/openwrt/lede/tmp/pip-build-env-vezp92h4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 52, in <module>
        File "<string>", line 29, in scm_config
        File "/home/king/openwrt/lede/tmp/pip-install-tt8lqps6/setuptools-scm_b7e62d5fd58443b6ad90dad118a9e3bc/src/setuptools_scm/__init__.py", line 15, in <module>
          from .version import format_version, meta
        File "/home/king/openwrt/lede/tmp/pip-install-tt8lqps6/setuptools-scm_b7e62d5fd58443b6ad90dad118a9e3bc/src/setuptools_scm/version.py", line 15, in <module>
          Version = pkg_resources.packaging.version.Version
      AttributeError: module 'pkg_resources' has no attribute 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by kissyouhunter** [comment]
我也试 编译x86 和 arm64的 都是这个报错
