### ISSUE TITLE
各位大佬能给看看这个编译报错是因为什么吗？

### ISSUE THREAD

**Issue by blueboyggh** [coolsnowwolf/lede#6361]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译过程中报错，多次重复编译都不行

### (2) 路由器型号和固件版本

A：N1盒子

### (3) 详细日志

A：[1/1014] ACTION //net:net_resources_grit(//build/toolchain/linux:clang_arm64_openwrt)
FAILED: gen/net/net_resources_grit.d.stamp gen/net/grit/net_resources.h gen/net/net_resources.pak gen/net/net_resources.pak.info 
/home/gao/openwrt/staging_dir/hostpkg/bin/python3 ../../build/util/python2_action.py ../../tools/grit/grit.py -i ../../net/base/net_resources.grd build -o gen/net --depdir . --depfile gen/net/net_resources_grit.d --write-only-new=1 --depend-on-stamp -E root_gen_dir=gen -E root_src_dir=../../ -D SHARED_INTERMEDIATE_DIR=gen -D scale_factors=2x -D _chromium -E CHROMIUM_BUILD=chromium -D desktop_linux -D toolkit_views -D use_aura -D use_nss_certs -D use_ozone -t linux2 -f gen/tools/gritsettings/default_resource_ids --assert-file-list obj/net/net_resources_expected_outputs.txt
Traceback (most recent call last):
  File "../../build/util/python2_action.py", line 27, in <module>
    sys.exit(subprocess.call([exe] + sys.argv[1:]))
  File "/home/gao/openwrt/staging_dir/hostpkg/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/gao/openwrt/staging_dir/hostpkg/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/gao/openwrt/staging_dir/hostpkg/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python2.7'
[3/1014] CXX obj/url/url/url_parse.o
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:144: /home/gao/openwrt/build_dir/target-aarch64_cortex-a53_musl/naiveproxy-88.0.4324.96-1/.built] Error 1
make[3]: Leaving directory '/home/gao/openwrt/feeds/helloworld/naiveproxy'
time: package/feeds/helloworld/naiveproxy/compile#52.74#4.80#88.50
make[2]: *** [package/Makefile:113: package/feeds/helloworld/naiveproxy/compile] Error 2
make[2]: Leaving directory '/home/gao/openwrt'
make[1]: *** [package/Makefile:107: /home/gao/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gao/openwrt'
make: *** [/home/gao/openwrt/include/toplevel.mk:224: world] Error 2

**Comment by blueboyggh** [comment]
这个问题解决了，应该是编译工具没装全
