### ISSUE TITLE
勾选open-vm-tools时，编译报错

### ISSUE THREAD

**Issue by Canary233** [coolsnowwolf/lede#9056]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：RT

### (2) 路由器型号和固件版本

A：X86_64

### (3) 详细日志

A：
```shell
Installing /home/lu/data/roms/lede/build_dir/hostpkg/glib-2.70.0/glib.supp to /home/lu/data/roms/lede/staging_dir/hostpkg/share/glib-2.0/valgrind
Traceback (most recent call last):
  File "/home/lu/data/roms/lede/staging_dir/host/lib/meson/meson.py/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/home/lu/data/roms/lede/staging_dir/host/lib/meson/meson.py/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/home/lu/data/roms/lede/staging_dir/host/lib/meson/meson.py/mesonbuild/minstall.py", line 594, in do_install
    self.apply_ldconfig(dm, destdir, d.is_cross_build, libdir)
  File "/home/lu/data/roms/lede/staging_dir/host/lib/meson/meson.py/mesonbuild/minstall.py", line 390, in apply_ldconfig
    apply_ldconfig(dm, libdir)
  File "/home/lu/data/roms/lede/staging_dir/host/lib/meson/meson.py/mesonbuild/minstall.py", line 270, in apply_ldconfig
    proc, out, err = Popen_safe(['ldconfig', '-v'])
  File "/home/lu/data/roms/lede/staging_dir/host/lib/meson/meson.py/mesonbuild/mesonlib/universal.py", line 1393, in Popen_safe
    p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'ldconfig'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-install 
/home/lu/data/roms/lede/staging_dir/host/bin/python3 /home/lu/data/roms/lede/staging_dir/host/lib/meson/meson.py install --no-rebuild
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:127: /home/lu/data/roms/lede/staging_dir/hostpkg/stamp/.glib2_installed] Error 1
make[3]: Leaving directory '/home/lu/data/roms/lede/feeds/packages/libs/glib2'
time: package/feeds/packages/glib2/host-compile#1.32#0.41#37.00
    ERROR: package/feeds/packages/glib2 [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/glib2/host/compile] Error 1
make[2]: Leaving directory '/home/lu/data/roms/lede'
make[1]: *** [package/Makefile:110: /home/lu/data/roms/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lu/data/roms/lede'
make: *** [/home/lu/data/roms/lede/include/toplevel.mk:230：world] 错误 2
```

**Comment by WYC-2020** [comment]
我这边刚编译试过 没问题，自己用万能大法重新试
