### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ydhang** [coolsnowwolf/lede#9346]
该日志中 `kmod-usb-net-rtl8152-vendor` 已成功编译、安装并打包（明确出现 `Packaged contents ...`），最后的 `package/Makefile` 返回码没有给出真正失败的包或命令。因此无法确认是 r8152 编译错误；请重新运行 `make package/lean/r8152/compile V=s`，并提供第一处实际错误。

**Comment by EnnawYang** [comment]
`Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on`

**Comment by Beginner-Go** [comment]
我看看

**Comment by Beginner-Go** [comment]
刚测了 不是r8125问题，自己排查吧
![image](https://user-images.githubusercontent.com/70857188/166425962-cb94e52f-7c13-446b-9cc3-e6bee989493b.png)

**Comment by EnnawYang** [comment]
> 刚测了 不是r8125问题，自己排查吧 

他这也不是8125的错误日志啊dalao（

**Comment by WYC-2020** [comment]
又是一个让人猜的问题，可以直接关闭这种issue

**Comment by angelandy** [comment]
```shell
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://github.com/upx/upx/releases/download/v3.95/upx-3.95-src.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:15 --:--:--     0
curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.cdn.openwrt.org/upx-3.95-src.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   169    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/upx-3.95-src.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   169    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/upx-3.95-src.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   169    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:36: /home/wu/work/lede/dl/upx-3.95-src.tar.xz] Error 2
make[3]: Leaving directory '/home/wu/work/lede/tools/upx'
time: tools/upx/compile#0.07#0.06#144.01
    ERROR: tools/upx failed to build.
make[2]: *** [tools/Makefile:162: tools/upx/compile] Error 1
make[2]: Leaving directory '/home/wu/work/lede'
make[1]: *** [tools/Makefile:158: /home/wu/work/lede/staging_dir/host/stamp/.tools_compile_yyynyynnyyyynyyyyyynyynnyynynyyyyyyyyyyyyyyyyyynynnyyyyyyyyyy] Error 2
make[1]: Leaving directory '/home/wu/work/lede'
make: *** [/home/wu/work/lede/include/toplevel.mk:230：world] 错误 2

```
我这边是各种404 啊

比如这个 ： https://mirror2.openwrt.org/sources/upx-3.95-src.tar.xz
确实是404 啊   不是被墙了

**Comment by cnstark** [comment]
不是被墙了，是这个文件没有了

**Comment by wivire** [comment]
我的编译20221001的源码，出现这错误：
make[3]: Entering directory '/home/u/lede/package/lean/upx'
mkdir -p /home/u/lede/dl
SHELL= flock /home/u/lede/tmp/.upx-2022-01-15.tar.gz.flock -c '          /home/u/lede/scripts/dl_github_archive.py --dl-dir="/home/u/lede/dl" --url="https://github.com/upx/upx.git" --version="a46b63817a9c6ad5af7cf519332e859f11558592" --subdir="upx-2022-01-15-a46b6381" --source="upx-2022-01-15.tar.gz" --hash="x" || (  echo "Checking out files from the git repository..."; mkdir -p /home/u/lede/tmp/dl && cd /home/u/lede/tmp/dl && rm -rf upx-2022-01-15-a46b6381 && [ \! -d upx-2022-01-15-a46b6381 ] && git clone  https://github.com/upx/upx.git upx-2022-01-15-a46b6381 && (cd upx-2022-01-15-a46b6381 && git checkout a46b63817a9c6ad5af7cf519332e859f11558592 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd upx-2022-01-15-a46b6381 && git log -1 --format='\''@%ct'\''` && rm -rf upx-2022-01-15-a46b6381/.git &&    tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c upx-2022-01-15-a46b6381 |       gzip -nc > /home/u/lede/tmp/dl/upx-2022-01-15.tar.gz && mv /home/u/lede/tmp/dl/upx-2022-01-15.tar.gz /home/u/lede/dl/ && rm -rf upx-2022-01-15-a46b6381; );     '
Traceback (most recent call last):
  File "/home/u/lede/scripts/dl_github_archive.py", line 19, in <module>
    import ssl
  File "/home/u/lede/staging_dir/hostpkg/lib/python3.10/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
Checking out files from the git repository...
Cloning into 'upx-2022-01-15-a46b6381'...
remote: Enumerating objects: 35389, done.
remote: Counting objects: 100% (934/934), done.
remote: Compressing objects: 100% (347/347), done.
remote: Total 35389 (delta 642), reused 823 (delta 587), pack-reused 34455
Receiving objects: 100% (35389/35389), 60.35 MiB | 13.02 MiB/s, done.
Resolving deltas: 100% (28366/28366), done.
fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592
make[3]: *** [Makefile:67: /home/u/lede/dl/upx-2022-01-15.tar.gz] Error 128
make[3]: Leaving directory '/home/u/lede/package/lean/upx'
time: package/lean/upx/host-compile#2.22#1.26#6.64
    ERROR: package/lean/upx [host] failed to build.
make[2]: *** [package/Makefile:114: package/lean/upx/host/compile] Error 1
make[2]: Leaving directory '/home/u/lede'
make[1]: *** [package/Makefile:110: /home/u/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/u/lede'
make: *** [/home/u/lede/include/toplevel.mk:230: world] Error 2

但是python3里import _ssl没问题呀
u@ubuntu:~$ python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _ssl
>>>

为啥会报No module named '_ssl'

**Comment by sunnysab** [comment]
> 我的编译20221001的源码，出现这错误： make[3]: Entering directory '/home/u/lede/package/lean/upx' mkdir -p /home/u/lede/dl SHELL= flock /home/u/lede/tmp/.upx-2022-01-15.tar.gz.flock -c ' /home/u/lede/scripts/dl_github_archive.py --dl-dir="/home/u/lede/dl" --url="https://github.com/upx/upx.git" --version="a46b63817a9c6ad5af7cf519332e859f11558592" --subdir="upx-2022-01-15-a46b6381" --source="upx-2022-01-15.tar.gz" --hash="x" || ( echo "Checking out files from the git repository..."; mkdir -p /home/u/lede/tmp/dl && cd /home/u/lede/tmp/dl && rm -rf upx-2022-01-15-a46b6381 && [ ! -d upx-2022-01-15-a46b6381 ] && git clone https://github.com/upx/upx.git upx-2022-01-15-a46b6381 && (cd upx-2022-01-15-a46b6381 && git checkout a46b63817a9c6ad5af7cf519332e859f11558592 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd upx-2022-01-15-a46b6381 && git log -1 --format='\''@%ct'\''` && rm -rf upx-2022-01-15-a46b6381/.git && tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c upx-2022-01-15-a46b6381 | gzip -nc > /home/u/lede/tmp/dl/upx-2022-01-15.tar.gz && mv /home/u/lede/tmp/dl/upx-2022-01-15.tar.gz /home/u/lede/dl/ && rm -rf upx-2022-01-15-a46b6381; ); ' Traceback (most recent call last): File "/home/u/lede/scripts/dl_github_archive.py", line 19, in import ssl File "/home/u/lede/staging_dir/hostpkg/lib/python3.10/ssl.py", line 99, in import _ssl # if we can't import it, let the error propagate ModuleNotFoundError: No module named '_ssl' Checking out files from the git repository... Cloning into 'upx-2022-01-15-a46b6381'... remote: Enumerating objects: 35389, done. remote: Counting objects: 100% (934/934), done. remote: Compressing objects: 100% (347/347), done. remote: Total 35389 (delta 642), reused 823 (delta 587), pack-reused 34455 Receiving objects: 100% (35389/35389), 60.35 MiB | 13.02 MiB/s, done. Resolving deltas: 100% (28366/28366), done. fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592 make[3]: *** [Makefile:67: /home/u/lede/dl/upx-2022-01-15.tar.gz] Error 128 make[3]: Leaving directory '/home/u/lede/package/lean/upx' time: package/lean/upx/host-compile#2.22#1.26#6.64 ERROR: package/lean/upx [host] failed to build. make[2]: *** [package/Makefile:114: package/lean/upx/host/compile] Error 1 make[2]: Leaving directory '/home/u/lede' make[1]: *** [package/Makefile:110: /home/u/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/u/lede' make: *** [/home/u/lede/include/toplevel.mk:230: world] Error 2
> 
> 但是python3里import _ssl没问题呀 u@ubuntu:~$ python3 Python 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import _ssl
> 
> 为啥会报No module named '_ssl'

我这边出现了 `fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592`，不知道怎么解决。 SSL 的导入没啥问题

**Comment by wscloudy** [comment]
我也是，git更新后出现的

**Comment by Ljzd-PRO** [comment]
我也是

**Comment by WangHan0711** [comment]
> ```shell
> + curl -f --connect-timeout 20 --retry 5 --location --insecure https://github.com/upx/upx/releases/download/v3.95/upx-3.95-src.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:02:15 --:--:--     0
> curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
> Download failed.
> + curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.cdn.openwrt.org/upx-3.95-src.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0   169    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
> curl: (22) The requested URL returned error: 404
> Download failed.
> + curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/upx-3.95-src.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0   169    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
> curl: (22) The requested URL returned error: 404
> Download failed.
> + curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/upx-3.95-src.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0   169    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
> curl: (22) The requested URL returned error: 404
> Download failed.
> No more mirrors to try - giving up.
> make[3]: *** [Makefile:36: /home/wu/work/lede/dl/upx-3.95-src.tar.xz] Error 2
> make[3]: Leaving directory '/home/wu/work/lede/tools/upx'
> time: tools/upx/compile#0.07#0.06#144.01
>     ERROR: tools/upx failed to build.
> make[2]: *** [tools/Makefile:162: tools/upx/compile] Error 1
> make[2]: Leaving directory '/home/wu/work/lede'
> make[1]: *** [tools/Makefile:158: /home/wu/work/lede/staging_dir/host/stamp/.tools_compile_yyynyynnyyyynyyyyyynyynnyynynyyyyyyyyyyyyyyyyyynynnyyyyyyyyyy] Error 2
> make[1]: Leaving directory '/home/wu/work/lede'
> make: *** [/home/wu/work/lede/include/toplevel.mk:230：world] 错误 2
> ```
> 
> 我这边是各种404 啊
> 
> 比如这个 ： https://mirror2.openwrt.org/sources/upx-3.95-src.tar.xz 确实是404 啊 不是被墙了

哥们解决了吗，我也遇到了这个问题

**Comment by wscloudy** [comment]
上一次编译已经没问题了，我clean之后重新更新就好了

**Comment by WangHan0711** [comment]
> 上一次编译已经没问题了，我clean之后重新更新就好了

好的，谢谢，我再试试

**Comment by whao123yahoo** [comment]
> > 我的编译20221001的源码，出现这错误： make[3]: Entering directory '/home/u/lede/package/lean/upx' mkdir -p /home/u/lede/dl SHELL= flock /home/u/lede/tmp/.upx-2022-01-15.tar.gz.flock -c ' /home/u/lede/scripts/dl_github_archive.py --dl-dir="/home/u/lede/dl" --url="https://github.com/upx/upx.git" --version="a46b63817a9c6ad5af7cf519332e859f11558592" --subdir="upx-2022-01-15-a46b6381" --source="upx-2022-01-15.tar.gz" --hash="x" || ( echo "Checking out files from the git repository..."; mkdir -p /home/u/lede/tmp/dl && cd /home/u/lede/tmp/dl && rm -rf upx-2022-01-15-a46b6381 && [ ! -d upx-2022-01-15-a46b6381 ] && git clone https://github.com/upx/upx.git upx-2022-01-15-a46b6381 && (cd upx-2022-01-15-a46b6381 && git checkout a46b63817a9c6ad5af7cf519332e859f11558592 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd upx-2022-01-15-a46b6381 && git log -1 --format='\''@%ct'\''` && rm -rf upx-2022-01-15-a46b6381/.git && tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c upx-2022-01-15-a46b6381 | gzip -nc > /home/u/lede/tmp/dl/upx-2022-01-15.tar.gz && mv /home/u/lede/tmp/dl/upx-2022-01-15.tar.gz /home/u/lede/dl/ && rm -rf upx-2022-01-15-a46b6381; ); ' Traceback (most recent call last): File "/home/u/lede/scripts/dl_github_archive.py", line 19, in import ssl File "/home/u/lede/staging_dir/hostpkg/lib/python3.10/ssl.py", line 99, in import _ssl # if we can't import it, let the error propagate ModuleNotFoundError: No module named '_ssl' Checking out files from the git repository... Cloning into 'upx-2022-01-15-a46b6381'... remote: Enumerating objects: 35389, done. remote: Counting objects: 100% (934/934), done. remote: Compressing objects: 100% (347/347), done. remote: Total 35389 (delta 642), reused 823 (delta 587), pack-reused 34455 Receiving objects: 100% (35389/35389), 60.35 MiB | 13.02 MiB/s, done. Resolving deltas: 100% (28366/28366), done. fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592 make[3]: *** [Makefile:67: /home/u/lede/dl/upx-2022-01-15.tar.gz] Error 128 make[3]: Leaving directory '/home/u/lede/package/lean/upx' time: package/lean/upx/host-compile#2.22#1.26#6.64 ERROR: package/lean/upx [host] failed to build. make[2]: *** [package/Makefile:114: package/lean/upx/host/compile] Error 1 make[2]: Leaving directory '/home/u/lede' make[1]: *** [package/Makefile:110: /home/u/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/u/lede' make: *** [/home/u/lede/include/toplevel.mk:230: world] Error 2
> > 但是python3里import _ssl没问题呀 u@ubuntu:~$ python3 Python 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> > > > > import _ssl
> > 
> > 
> > 为啥会报No module named '_ssl'
> 
> 我这边也出现了 `fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592`，不知道怎么解决。 SSL 的导入没啥问题

wo ye yudaole tongyang de wenti.laoge ni shi zenme jiejue de ?
