### ISSUE TITLE
编译报错 cannot load such file -- optparse

### ISSUE THREAD

**Issue by swq93** [coolsnowwolf/lede#9492]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
*  没有类似的issue

### (1) 具体问题

编译报错

### (2) 路由器型号和固件版本

x86软路由

### (3) 详细日志

fstack-protector-strong -pie
        SOLIBS = -lz -lpthread -lrt -lrt -ldl -lcrypt -lm
        LANG = C
        LC_ALL = C
        LC_CTYPE =
        MFLAGS = -w -j1
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

./tool/file2lastrev.rb:6:in `require': cannot load such file -- optparse (LoadError) from ./tool/file2lastrev.rb:6:in `<main>'
make[4]: *** [uncommon.mk:1191: revision.tmp] Error 1
make[4]: Leaving directory '/mnt/wsl/PHYSICALDRIVE1p1/lede/build_dir/hostpkg/ruby-3.1.2'
make[3]: *** [Makefile:1156: /mnt/wsl/PHYSICALDRIVE1p1/lede/build_dir/hostpkg/ruby-3.1.2/.built] Error 2
make[3]: Leaving directory '/mnt/wsl/PHYSICALDRIVE1p1/lede/feeds/packages/lang/ruby'
time: package/feeds/packages/ruby/host-compile#0.30#0.10#0.32
    ERROR: package/feeds/packages/ruby [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/ruby/host/compile] Error 1
make[2]: Leaving directory '/mnt/wsl/PHYSICALDRIVE1p1/lede'
make[1]: *** [package/Makefile:110: /mnt/wsl/PHYSICALDRIVE1p1/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/mnt/wsl/PHYSICALDRIVE1p1/lede'
make: *** [/mnt/wsl/PHYSICALDRIVE1p1/lede/include/toplevel.mk:230: world] Error 2

**Comment by jinjin327** [comment]
我也一样哎
